### PR TITLE
Issue 101: Fix lint

### LINKED ISSUE #100: Why is `sdlog = exp(sdlog)`?
This line seems strange:

https://github.com/epinowcast/epidist/blob/f308cd0cdae3b0c35113eb23f1c08654d665c035/R/fitting-and-postprocessing.R#L173

Any idea what's happening there @seabbs @parksw3?

Also in `add_natural_scale_mean_sd` we have:

https://github.com/epinowcast/epidist/blob/f308cd0cdae3b0c35113eb23f1c08654d665c035/R/fitting-and-postprocessing.R#L132-L140

What about reusing `mean` on L137?

### LINKED ISSUE #101: Fix linting
Linting checks are currently failing and the mix of old and new issues makes the CI broadly useless for review support (for example see #95). We either need to address all linting issues urgently or commit to dealing with those flagged by the lint in a given PR so that it passes. 

If the latter I will make linting required in PRs (hence it will block) but if the former we need a PR to address this (and then I will mak linting required).

### PR DESCRIPTION
**Pull request by athowes**
## Description

This PR closes #101, #63, #100.

* #101: fixes all linting errors, using `roxyglobals`
* #63: solution is to use `roxyglobals`
* As a part of this issue, because it also presented a linting error, I fixed #100

Remaining lint fails are to do with use of "." and unsure how to resolve atm:

image

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by athowes** [comment]
I'm confused by this `R-CMD-check / macOS-latest` fail on runing the vignette. With the package built as in this PR the vignette works ok for me locally (including fresh session). Any ideas what it could be?

**Review by seabbs — COMMENTED** [review]
Looks good. Can you make an issue for `.` resolution though I think adding manually will do it if can't use the roxyglobals approach. 

The mac failure is due to cmdstan installation issues on CI from reading the error message so seems likely to be unrelated to this PR

**Comment by athowes** [comment]
Tried this solution: https://github.com/Rdatatable/data.table/issues/5436 (replace `.` by `list`)

**Comment by seabbs** [comment]
> I tried putting "." into the globals.R file as created 

If your list doesn't help all you need to do is make another globals util somewhere that isn't an automated file.

**Comment by seabbs** [comment]
Or use this: https://github.com/anthonynorth/roxyglobals

and try @global .

**Comment by athowes** [comment]
Passed `lint` now and have checked that the `list` swap works (for `extract_lognormal_draws`).

**Review by seabbs — APPROVED** [review]

**Pull request merged**
