### PR TITLE
Issue 163: Create `epidist_diagnostics`

### PR DESCRIPTION
**Pull request by athowes**
## Description

This draft PR will close issue #163.

## Checklist

- [ ] My PR is based on a package issue and I have explicitly linked it.
- [ ] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [ ] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by athowes** [comment]
This is incomplete but I'd be interested in feedback before finishing off. In my mind remaining things are:

* [ ] Add time taken
* [ ] Complete unit tests
* [ ] Double check that no useful diagnostics really are available for methods outside `"sampling"`
* [ ] Investigate why `epidist_diagnostics` seems to take a reasonably long time (can it be quicker?)
* [ ] Document functions
* [ ] Not really happy with the placement of functions into files / families but I think it's a wider issue and should be rethought more broadly (perhaps mention this in issue about it #162)

**Comment by seabbs** [comment]
Is this stil la draft or ready for review?

**Comment by athowes** [comment]
Just need to fix tests then will be ready for review. Will message you or tag

**Comment by athowes** [comment]
Ready! @seabbs

**Review by seabbs — APPROVED** [review]
Nice. LGTM. The workflow (fit -> diagnostics) is much better.

**Pull request merged**
