### PR TITLE
Issue 14: Passing `R CMD CHECK`

### LINKED ISSUE #14: Get Rmd check passing
As a first step before any new code development we need to make sure Rmd check is either passing or that we have clear issues for each problem which is blocked by other areas of the development.

### PR DESCRIPTION
**Pull request by athowes**
## Description

This PR closes #14.

The part that I am unsure of is the vignette building. But it seems like I didn't need to commit those files for it to pass.

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by athowes** [comment]
The lint is failing because I altered a lot of files here, and a lot of them have linter issues. A lot of this will be solved by #63.

The `R-CMD-as-cran-check` I think is failing because I'm not passing in something to the `cmdstanr::set_cmdstan_path()` (but I don't know what I would be passing in here).

**Comment by athowes** [comment]
I removed the `VignetteBuilder` field from `DESCRIPTION` hoping to pass `R-CMD-as-cran-check` but this led to failing `R-CMD-check`:

```
❯ checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
Error: Error: R CMD check found WARNINGs
    ‘epidist.Rmd’ ‘references.bib’
  Package has no Sweave vignette sources and no VignetteBuilder field.
```

**Comment by athowes** [comment]
Using: https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by seabbs** [comment]
I think the as cran R cmd action itself needs to be updated vs the description

**Comment by seabbs** [comment]
I don't think we want precomputed vignettes right now as they come up a bunch of other problems. I favour moving this to an issue and stopping the as CRAN cmd check from building vignettes

**Comment by athowes** [comment]
> I favour moving this to an issue and stopping the as CRAN cmd check from building vignettes

I don't have strong opinion either way so happy to do this.

**Comment by athowes** [comment]
Added https://github.com/epinowcast/epidist/issues/96.

**Comment by athowes** [comment]
Trying to copy from: https://github.com/MichaelChirico/r-ci-samples/blob/3c47819d9bc818c5f77a004b2b8312b73c4255a5/github-actions/brms/R-CMD-check.yaml#L82

**Review by seabbs — APPROVED** [review]
LGTM - making R cmd check required from now on. Now just need the linting sorted!

**Pull request merged**
