### PR TITLE
Issue 78: Location of Stan code

### LINKED ISSUE #78: User interaction with Stan code
The #70 PR raised some issues about how we want the user to be able to interact with the Stan code passed in for specific models (in this case `ltcad`). This will be an ongoing issue as more models are added.

Currently:

* `epidist_stancode` method available and exposed
* Takes as argument at least the data, perhaps also family and eventually priors

Questions:

* Extent to which we show and explain the custom Stan code
* Extent to which we expect users to make alterations to custom Stan code

Moving forward:

* I suggest a first thing will be to document via the returns of `epidist_stancode.epidist_ltcad` what the different objects are and how they change the model. This would then allow the user to (perhaps) alter the output of that Stan code
* Think / discuss how we want this to be handled in future (sorry for vague)

### PR DESCRIPTION
**Pull request by athowes**
## Description

This PR closes #78.

I have added issues for additional complexities:

* #123
* #124

There are failing checks but they are unrelated to the code changes I think.

## Checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [x] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [x] I have tested my changes locally.
- [x] I have added or updated unit tests where necessary.
- [x] I have updated the documentation if required.
- [x] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [x] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by athowes** [comment]
* Generate docs
* New issue about `stats::` or in `roxygen2`

**Review by seabbs — COMMENTED** [review]
Aside from already flagged changes this looks good to me

**Comment by athowes** [comment]
Note that if the unit tests PR contains calling of this function and code would be changed to have this merge.

**Comment by athowes** [comment]
Outstanding issues addressed and I believe ready to merge!

**Review by seabbs — APPROVED** [review]
Nice.

**Pull request merged**
