### PR TITLE
Simplify epred

### PR DESCRIPTION
**Pull request by seabbs**
This PR is unlinked to an issue. In reviewing the current functionality needed for a family I slightly simplified the current code.  

Unrelated to this PR there are lots of ways we can streamline adding families and sharing support across models and across families (for models) it looks like which is great.

### CODE REVIEW

**Comment by seabbs** [comment]
Hmm interesting. The with approch is directly based on the `lognormal` code from `brms` so curious why this fails tests (but not otherwise?)

**Comment by athowes** [comment]
I'll go in and look at this.

**Comment by athowes** [comment]
```r
> str(prep$dpars)
List of 2
 $ mu   :List of 10
  ..$ family:List of 16
  .. ..$ family           : chr "custom"
  .. ..$ link             : chr "identity"
  .. ..$ name             : chr "latent_lognormal"
  .. ..$ dpars            : chr [1:2] "mu" "sigma"
  .. ..$ lb               :List of 2
  .. .. ..$ mu   : chr NA
  .. .. ..$ sigma: chr "0"
  .. ..$ ub               :List of 2
  .. .. ..$ mu   : chr NA
  .. .. ..$ sigma: chr NA
  .. ..$ type             : chr "real"
  .. ..$ vars             : chr [1:3] "pwindow" "swindow" "vreal1"
  .. ..$ loop             : logi FALSE
  .. ..$ specials         : chr(0) 
  .. ..$ log_lik          : NULL
  .. ..$ posterior_predict: NULL
  .. ..$ posterior_epred  : NULL
  .. ..$ env              :<environment: 0x12f030b38> 
  .. ..$ normalized       : chr ""
  .. ..$ link_sigma       : chr "log"
  .. ..- attr(*, "class")= chr [1:3] "customfamily" "brmsfamily" "family"
  ..$ ndraws: int 4000
  ..$ nobs  : int 500
  ..$ fe    :List of 2
  .. ..$ X: num [1:500, 1] 1 1 1 1 1 1 1 1 1 1 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : chr [1:500] "1" "2" "3" "4" ...
  .. .. .. ..$ : chr "Intercept"
  .. .. ..- attr(*, "assign")= int 0
  .. ..$ b: num [1:4000, 1] 1.75 1.77 1.73 1.76 1.76 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ draw    : chr [1:4000] "1" "2" "3" "4" ...
  .. .. .. ..$ variable: chr "b_Intercept"
  .. .. ..- attr(*, "nchains")= int 4
  ..$ sp    : list()
  ..$ cs    : list()
  ..$ sm    : list()
  ..$ gp    : list()
  ..$ re    : list()
  ..$ ac    : list()
  ..- attr(*, "class")= chr "bprepl"
 $ sigma: num [1:4000] 0.498 0.502 0.486 0.469 0.488 ...
```

**Comment by athowes** [comment]
I think because it's a custom family it's more complicated, so reverting back to the `get_dpars` version (and keeping the line saving in the gamma case).

**Review by athowes — APPROVED** [review]

**Review by athowes — APPROVED** [review]

**Pull request merged**
