### PR TITLE
Issue #294: Switch to using family = "lognormal" rather than lognormal()

### PR DESCRIPTION
**Pull request by athowes**
## Description

This PR closes https://github.com/epinowcast/epidist/issues/294.

## Checklist

- [ ] My PR is based on a package issue and I have explicitly linked it.
- [ ] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [ ] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by athowes** [comment]
> review ready?

Just waiting for possible pass checks. Feel free to look at this and give feedback before, will tag as ready for review.

**Review by seabbs — APPROVED** [review]
Looks good to me.

**Comment by seabbs** [comment]
Hmm not sure what is causing this. Seems hard to imagine its this PR but we aren't seeing it elsewhere.

**Comment by athowes** [comment]
> Hmm not sure what is causing this. Seems hard to imagine its this PR but we aren't seeing it elsewhere.

Yes I imagine it's this PR. Will look

**Review by seabbs — COMMENTED** [review]
Looking at CI it seems like the build failure is:  389-430 in the ebola vignette. That is a chunk that plots the discrete pmfs.

**Comment by seabbs** [comment]
I just killed the windows cmdstan cache just in case it was that

**Comment by seabbs** [comment]
I also see that there is a new version of Rtools that I have bumped to

**Comment by athowes** [comment]
@seabbs looks like this fixed it!

**Pull request merged**
