### PR TITLE
Issue 204: Remove family as class

### LINKED ISSUE #204: Use class name for families that avoids clashes
> I think if this is the name taken from brms directly which I think it is it could lead to collisions with other packages. Happy for this to be dealt with in an issue.

_Originally posted by @seabbs in https://github.com/epinowcast/epidist/pull/170#discussion_r1695079568_

e.g. `epidist_lognormal` over `lognormal`.

### PR DESCRIPTION
**Pull request by athowes**
## Description

This PR closes #204.

It turns out that I think actually no where in the code are we using the family class so far, so I removed it.

## Checklist

- [ ] My PR is based on a package issue and I have explicitly linked it.
- [ ] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [ ] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
How are we going to do add_mean_sd without this or is this a remove for now?

**Comment by athowes** [comment]
`add_mean_sd` doesn't use this anywhere at the moment.

Also, `fit` stores the `family` information in it anyway, so we don't need it (we can just `class(...) <- fit$family$name`).

**Comment by seabbs** [comment]
My point was we need a custom family for samples to then apply the class for add_mean_sd

> Also, fit stores the family information in it anyway, so we don't need it (we can just class(...) <- fit$family$name).

We can however use this for now but it won't work if we want to dispatch on a s3 method

**Review by seabbs — APPROVED** [review]

**Comment by athowes** [comment]
It's the samples which should have some kind of class, not the `fit` seems like. Unless it'd be both

**Comment by seabbs** [comment]
it is wether or not you need a family based extraction function to get the samples to have the right class

**Comment by athowes** [comment]
I don't think that you do. Or that the extent to which you do then `brms` can handle it. Will see with implementing the #188

**Pull request merged**
