### PR TITLE
Issue #331: Add pre-commit and lintr configuration

### LINKED ISSUE #331: Add precommit hooks
https://lorenzwalthert.github.io/precommit/index.html

### PR DESCRIPTION
**Pull request by athowes**
## Description

This PR closes #331. It adds the pre-commit and lintr configuration from `primarycensored` and gets all files passing through those settings (after some exclusions are made).

Remains to:

* [x] Get tests passing with more stringent `expect_identical` calls
* [x] Add pre-commit to CI/CD.

## Checklist

- [ ] My PR is based on a package issue and I have explicitly linked it.
- [ ] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [ ] I have read the [contribution guidelines](https://github.com/epinowcast/.github/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

### CODE REVIEW

**Comment by athowes** [comment]
@seabbs should we be adding passing the precommit to CI?

**Comment by athowes** [comment]
> we can do

Is it your preference that we add passing precommit to CI?

**Comment by seabbs** [comment]
I don't feel that strongly but I am certainly not against it

**Comment by athowes** [comment]
@seabbs this is kind of annoying to get over the line, but it already contains useful work in there. Could we consider merge and then follow up issues about the pain points on the pre-commit?

**Comment by athowes** [comment]
image

🥳

**Comment by athowes** [comment]
Was a bit of a mess getting there but I think this should pass now. Unsure about "require" precommit pass vs it being a check but not required? (Both how to change and if we should, though how to change I can easily find)

**Review by seabbs — APPROVED** [review]
Amazing looks great!!  Shall we just watch how useful it is and then make it required when we are clear. THis is a really nice clean up.

**Pull request merged**
